### ISSUE TITLE
Error when trying to execute "flutter run"

### ISSUE THREAD

**Issue by RafaelGondi** [Nicuz/Calcolapizza#3]
After cloning the project, when I tried to compile and run the project I got the error "A problem occurred evaluating project ':app'. > path may not be null or empty string. path='null'", that i solved commented signingConfig, buildTypes in the "build.grade" file, a solution that can be found here: 

https://github.com/transistorsoft/flutter_background_geolocation/issues/18

After that I got the error  "Compiler message:                                                       
lib/ui/screens/dough_page.dart:2:8: Error: Error when reading 'lib/facebook_ads.dart': No such file or directory import 'package:calcolapizza/facebook_ads.dart';"
even though I ran "flutter pub get"

Can you help me running the project?
Thanks in advance

**Comment by Nicuz** [comment]
Hi Rafael, facebook_ads.dart is a file that contains my Facebook Audience Networks' ids. Comment the following lines to disable the ads and try again.

line 16
```Dart
FacebookAudienceNetwork.init(testingId: facebookTestingId);
```

lines 145-154
```Dart
FacebookBannerAd(
                            placementId: facebookPlacementId,
                            listener: (BannerAdResult result, dynamic value) {
                              print("Banner Ad: $result --> $value");
                              doughDetailsProvider.setShowAdsDivider =
                                  result.toString() == "BannerAdResult.ERROR"
                                      ? false
                                      : true;
                            },
                          )
```
